export const appConstants = {
  GET_CONTENT_SLOTS_SUCCESS: "GET_CONTENT_SLOTS_SUCCESS",
  UPLOAD_PRODUCT_SUCCESS: "UPLOAD_PRODUCT_SUCCESS",
  VALIDATE_SUCCESS: "VALIDATE_SUCCESS",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  SAVE_PRODUCT_SUCCESS: "SAVE_PRODUCT_SUCCESS"
};
